abeilles/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from abeilles.views import Sample

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),

    # Account
    path('accounts/', include('users.urls')),

    # Services
    path('services/', include('services.urls')),

    # Basket
    path('panier/', include('basket.urls')),

    # Posts
    path('actualites/', include('posts.urls')),

    # Pages
    path('', include('pages.urls')),

    # CK Editor
    path('ckeditor/', include('ckeditor_uploader.urls')),

    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from pages.models import Homepage
from django.urls import path
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    # AAE
    path('association', views.page_association, name='association'),
    # path('notre-equipe', views.page_team, name='team'),
    path('missions-valeurs-engagement', views.page_missions, name='missions'),
     path('rayonnement-territorial', views.page_territorial_influence, name='territorial-influence'),
    # path('nos-valeurs', views.page_values, name='values'),
    # path('nos-partenaires', views.page_partners, name='partners'),
    # garden
    path('jardin', views.page_garden, name='garden'),
    path('jardin/projet', views.page_garden_project, name='garden-project'),
    # jobhunt
    path('demandeur-emploi', views.page_jobhunt, name='jobhunt'),
    # services
    path('services-pour-professionnels', views.page_services_pro, name='services_pro'),
    path('services-pour-particuliers', views.page_services_ind, name='services_ind'),
    # contact
    path('contact', views.contact, name='contact'),
    # static pages
    path('cookies', TemplateView.as_view(
            template_name='pages/cookies.html',
            extra_context={
                "full_text_page": True,
            }), name="cookies"),
    path('confidentiality', TemplateView.as_view(
            template_name='pages/confidentiality.html',
            extra_context={
                "full_text_page": True,
            }), name="confidentiality"),
    path('mentions-legales', TemplateView.as_view(
            template_name='pages/legal-notice.html',
            extra_context={
                "full_text_page": True,
            }), name="legal-notice"),
    # not used
    # path('<page_slug>/', views.page_custom, name='page'),
]

services/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    # path('', views.index, name='services'),
    path('service/<str:service_slug>/', views.service, name="single-service"),
    

    # new URLs
    # path('professionnels/', views.services_professionnels, name="services_pro2"),

    # path('professionnels/', views.services_pro, name="services_pro2"),
    # path('particuliers/', views.services_ind, name="services_ind2"),
    # path('professionnels/', TemplateView.as_view(template_name='services/test.html'), name="servicespro"),

    # path('<str:job>/demande', views.single, name="ask-service"),

    path('<str:category_slug>/', views.category, name="category"),
]

services/forms.py
import datetime
from django import forms
from django.forms.widgets import TextInput, EmailInput
from django.http import request 
from .models import Category, Service
from django.db.models import Q


class BaseServiceForm(forms.Form):
 
    # service = forms.CharField(
    #         max_length=50,
    #         widget=forms.HiddenInput()
    # )

    
    # Vos coordonées
    name = forms.CharField(
            max_length=30,
            label="",
            widget=forms.TextInput(attrs={'placeholder': f'Votre nom*'}),
        )
    location = forms.CharField(
            max_length=30,
            label="",
            widget=forms.TextInput(attrs={'placeholder': 'Ville d\'intervention*'}),
        )
    company = forms.CharField(
            max_length=20,
            label="",
            widget=forms.TextInput(attrs={'placeholder': 'Votre entreprise*'}),
            required=False,
        )
    email = forms.EmailField(
            label="",
            widget=forms.EmailInput(attrs={'placeholder': 'Votre email'}),
            required=False,
        )
    phone = forms.CharField(
            max_length=20,
            label="",
            widget=forms.TextInput(attrs={"placeholder":"Numéro de téléphone*"})
        )

    # def __init__(self, exclude_id):
    #     super().__init__()

    #     print('\n****\n', 'yo', '\n****\n',)
    #     self.fields['extra_services'] = forms.ModelMultipleChoiceField(
    #     label=f"J'ai aussi besoin de ...",
    #     queryset=Service.objects.filter(target="PARTICULIER", available=True).exclude(id=3),
    #     widget=forms.CheckboxSelectMultiple,
    #     initial=0,
    # )

    extra_services = forms.ModelMultipleChoiceField(
            # label=f"J'ai surtout besoin de...",
            queryset=Service.objects.filter(category__target="PARTICULIER", available=True),
            widget=forms.CheckboxSelectMultiple,
            initial=0,
        )
    


class ServiceForm(BaseServiceForm):
    def __init__(self, *args, s_category, excluded_id, **kwargs):
        # self.excluded_id = excluded_id

        super().__init__(*args, **kwargs)
        self.fields['extra_services'] = forms.ModelMultipleChoiceField(
            label=f"J'ai aussi besoin de...",
            queryset=Service.objects.filter(
                    # category__target="PARTICULIER",
                    available=True,
                    category=s_category,
                    ).exclude(id=excluded_id),
            widget=forms.CheckboxSelectMultiple,
            initial=0,
        )


class CategoryForm(forms.Form):
    # Vos coordonées
    name = forms.CharField(
            max_length=20,
            label="",
            widget=forms.TextInput(attrs={'placeholder': f'Votre nom*'}),
        )
    company = forms.CharField(
            max_length=20,
            label="",
            widget=forms.TextInput(attrs={'placeholder': 'Votre entreprise*'}),
        )
    email = forms.EmailField(
            label="",
            widget=forms.EmailInput(attrs={'placeholder': 'Votre email'}),
            required=False,
        )
    


class CategoryForm2(BaseServiceForm):
    def __init__(self, *args, s_category, **kwargs):
        # self.excluded_id = excluded_id

        super().__init__(*args, **kwargs)
        self.fields['extra_services'] = forms.ModelMultipleChoiceField(
            label=f"J'ai besoin de ...",
            required=False,
            queryset=Service.objects.filter(
                    # category__target="PARTICULIER",
                    available=True,
                    category=s_category,
                    ),
            widget=forms.CheckboxSelectMultiple,
            initial=0,
        )

services/views.py
import datetime
from django.shortcuts import render
from django.core.mail import send_mail
from django.conf import settings
from .models import Service, Category
from .forms import ServiceForm, CategoryForm, CategoryForm2
from pages.models import PageServices, PageServicesPro, PageServicesInd
# from questions.models import QuestionServicesInd, QuestionServicesPro
from settings.models import ContactEmail, RecipientEmail
from questions.models import (
        QuestionServicesInd, QuestionServicesPro,
    )
from honeypot.decorators import check_honeypot

from django.contrib import messages

# def index(request):
#     context = {}
#     context["page_class"] = "packages"
#     context["packages"] = []

#     for app_type in Package.AppTypes:
#         packages_part = (
#             app_type.label, Package.objects.filter(app_type=app_type))
#         context["packages"].append(packages_part)

#     return render(request, 'packages/index.html', context)

# for services in Category.name:


# {% regroup services by category as groups %}
# {% for group in groups %}
# {% endfor %}


def index(request):
    
    page = PageServices.objects.first()
    services_professionnels = []
    services_particuliers = []

    for category in Category.objects.all():
        pro_services_by_category = Service.objects.filter(
                category__target="PROFESSIONNEL",
                category=category,
            )
        pro_services_by_category_count = pro_services_by_category.count()
        if pro_services_by_category_count > 0:
            services_professionnels.append(pro_services_by_category)

    for category in Category.objects.all():
        ind_services_by_category = Service.objects.filter(
                category__target="PARTICULIER",
                category=category,
            )
        ind_services_by_category_count  = ind_services_by_category.count()
        if ind_services_by_category_count > 0:
            services_particuliers.append(ind_services_by_category)

    context = {
        "meta_title": page.meta_title,
        "meta_description": page.meta_description,
        "title": page.title,
        "headline": page.headline,
        "featured_image": page.featured_image,
        "body1": page.body1,
        "image1": page.image1,
        "body2": page.body2,
        "image2": page.image2,
        "body3": page.body3,
        "image3": page.image3,
        "services_professionnels": services_professionnels,
        "services_particuliers": services_particuliers,
        "page_class": "services",
    }

    return render(request, 'services/index.html', context)


@check_honeypot(field_name='firstname')
def category(request, category_slug):

    category = Category.objects.get(slug=category_slug)
    services = Service.objects.filter(
            category=category,
            available=True,
        )
    if category.target == "PARTICULIER":
        questions = QuestionServicesInd.objects.all()
    else:
        questions = QuestionServicesPro.objects.all()

    context = {
        "meta_title": category.meta_title,
        "meta_description": category.meta_description,
        "title": category.title,
        "headline": category.headline,
        "featured_image": category.featured_image,
        "body1": category.body1,
        "image1": category.image1,
        "services": services,
        "page_class": f"service category {category.target.lower()}",
        "meta_title": f"prestation de service : {category.title.lower()}",
        "questions": questions,
    }

    if request.method == 'POST':
        context["form_category"] = CategoryForm2(
                request.POST,
                s_category=category.id,
            )
        # Form is valid
        if context["form_category"].is_valid():
            # Get Email for sending and recipients emails 
            sender = ContactEmail.objects.first()
            recipients = [ recipient.email for recipient in RecipientEmail.objects.all() ]
            # Get message elements:
            name = context["form_category"].cleaned_data['name']
            company = context["form_category"].cleaned_data['company']
            email = context["form_category"].cleaned_data['email']

            extra_services = list(context["form_category"].cleaned_data['extra_services'])

            # Message for Abeilles
            if extra_services:
                extra_services_text = f"""
Le(s) service(s) suivants m'intéress(ent) particulièrement :
{ ', '.join([service.name for service in extra_services]) }
"""
            else:
                extra_services_text = ""
            message = f"""
Message de {email},
Demande de service envoyée le {datetime.datetime.now()},
Catégorie de services demandée : {category.name}
{extra_services_text}
--
Nom : {name}
Société : {company}
Email : {email}
"""         
            # Send Email to Abeilles
            for mail in recipients:
                send_mail(f"[Demande de service] {category.name}", message, sender.email, [mail])

            # Message for User
            if extra_services:
                extra_services_text = f"""
Le(s) service(s) suivants qui vous intéress(ent) particulièrement :
{ ', '.join([service.name for service in extra_services]) }
"""
            else:
                extra_services_text = ""
            message = f"""
Merci pour votre demande de service !
Voici la demande que vous avez formulée le {datetime.datetime.now()} :

Catégorie de services demandée : {category.name}
{extra_services_text}
--
Nom : {name}
Société : {company}
Email : {email}
"""
            # Senf copy to User
            recipients = [email]
            for mail in recipients:
                send_mail("Votre demande de service", message, sender.email, [mail])
            context["form_category"] = CategoryForm2(
                    s_category=category.id,
                )
            messages.success(request, "Votre demande a bien été envoyée")
            render(request, 'services/category.html', context)
        # Form not not valid
        else:
            messages.error(request, "Il y a eu un problème, veuillez réessayer")
            render(request, 'services/category.html', context)
    else:
        context["form_category"] = CategoryForm2(
            s_category=category.id,
        )
    return render(request, 'services/category.html', context)


def service(request, service_slug):
    """
    NOT USED
    """
    context = {}
    context["service"] = Service.objects.get(slug=service_slug)
    context["page_class"] = "service",

    if request.method == 'POST':
        context["form"] = ServiceForm(
                request.POST,
                s_category=context["service"].category.id,
                excluded_id=context["service"].id,
            )
        # Form is valid
        if context["form"].is_valid():
            sender = ContactEmail.objects.first()
            subject = "Demande de service"
            name = context["form"].cleaned_data['name']
            company = context["form"].cleaned_data['company']
            email = context["form"].cleaned_data['email']
            extra_services = list(context["form"].cleaned_data['extra_services'])
            message = f"""
Message de {email},
Demande de service envoyée le {datetime.datetime.now()},
--
Nom : {name}
Société : {company}
Email : {email}
Le(s) service(s) suivants m'intéress(ent) aussi par :
{ ', '.join([service.name for service in extra_services]) }
""" 
            recipients = [email, sender.email]
            for mail in recipients:
                send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [mail])
            messages.success(request, "Votre demande a bien été envoyée")
            render(request, 'services/single.html')
        # Form not not valid
        else:
            messages.error(request, "Il y a eu un problème, veuillez réessayer")
            render(request, 'services/single.html', context)
    else:
        print(f"***\ncontext['service'].category.id: { context['service'].category.id }\n***")
        context["form"] = ServiceForm(
                s_category=context["service"].category.id,
                excluded_id=context["service"].id
            )

    return render(request, 'services/single.html', context)


# Attempts

# def services_pro(request):
    
#     page = PageServicesPro.objects.first()
#     services_professionnels = []

#     for category in Category.objects.all():
#         pro_services_by_category = Service.objects.filter(
#                 category__target="PROFESSIONNEL",
#                 category=category,
#             )
#         pro_services_by_category_count = pro_services_by_category.count()
#         if pro_services_by_category_count > 0:
#             services_professionnels.append(pro_services_by_category)

#     context = {
#         "meta_title": page.meta_title,
#         "meta_description": page.meta_description,
#         "title": page.title,
#         "headline": page.headline,
#         "featured_image": page.featured_image,
#         "body1": page.body1,
#         "image1": page.image1,
#         "body2": page.body2,
#         "image2": page.image2,
#         "body3": page.body3,
#         "image3": page.image3,
#         "services_professionnels": services_professionnels,
#         "page_class": "services-pro",
#     }

#     return render(request, 'services/index-pro.html', context)


# def services_ind(request):
    
#     page = PageServicesInd.objects.first()
#     services_particuliers = []

#     for category in Category.objects.all():
#         ind_services_by_category = Service.objects.filter(
#                 category__target="PARTICULIER",
#                 category=category,
#             )
#         ind_services_by_category_count  = ind_services_by_category.count()
#         if ind_services_by_category_count > 0:
#             services_particuliers.append(ind_services_by_category)

#     context = {
#         "meta_title": page.meta_title,

pages/templates/pages/contact.html
{% extends "core.html" %}

{% block content %}
{% include 'pages/generic.html' %}
{% endblock %}

pages/templates/pages/form-category.html
{% load honeypot %}

<div id="category-form" class="popup">
    <form class="form" action="" method="post">
        <a href="#" class="close close-bk-form" title="Fermer la pop-up">❌</a>
        <p>Demande de service</p>
        <h2 class="title h2">{{ title }}</h2>
        <hr>
        <p class="info valid center demand-confirmation" hidden="">Votre demande a bien été envoyée, nous vous répondrons dans les meilleurs délais.</p>
        <p class="info warning center check-something" hidden="">Il y a eu une erreur lors de l'envoi, notre e-mail a@b.c reste disponible</p>
        {% csrf_token %}
        {% render_honeypot_field "firstname" %}
        <p>{{ form_category.name }}</p>
        {% if page_class == "service category professionnel" %}
        <p>{{ form_category.company }}</p>
        {% else %}
        <p>
            <input hidden type="text" name="company" placeholder="Votre entreprise*" maxlength="20" required="" id="id_company" value="N/A">
        </p>
        {% endif %}
        <p>{{ form_category.location }}</p>
        <p>{{ form_category.email }}</p>
        <p>{{ form_category.phone }}</p>
        <p>{{ form_category.all }}</p>
        <details class="faq-qr">
            <summary class="link question">Préciser les services qui m'intéressent ?</summary>
            <p>{{ form_category.extra_services.label }}</p>
            {{ form_category.extra_services }}
        </details>
        <input class="btn btn-lblue" type="submit" value="Je fais une demande de service" />
    </form>
</div>

pages/templates/pages/form-contact.html
{% load honeypot %}

{% if form.errors %}
    {% for field in form %}
    {% for error in field.errors %}
    <div class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
    </div>
    {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
    </div>
    {% endfor %}
{% endif %}

    <p class="info valid center demand-confirmation" hidden="">Votre message a bien était envoyé, nous vous répondrons dans les meilleurs délais</p>
    <p class="info warning center check-something" hidden="">Une erreur c'est produite lors de l'envoi, notre e-mail <a href="mailto:contact@asso-abeilles.fr">contact @ asso-abeilles.fr</a> reste disponible</p>
    <form class="form" action="" method="post">
        {% csrf_token %}
        {% render_honeypot_field "firstname" %}
        {% comment %} {{ form.as_p }} {% endcomment %}
        <input type="radio" name="type" value="1" required="" id="id_type_0" checked="checked" hidden>
        <input type="radio" name="type" value="2" required="" id="id_type_1" hidden>
        <div id="contact-form-type">
            <label for={{ form.type.id_for_label }}>Vous êtes :</label>
            <ul id="id-type">
                <li>
                    <label id="id_type_0_label" class="radio radio-button" for="id_type_0">Un particulier</label>
                </li>
                <li>
                    <label id="id_type_1_label" class="radio radio-button" for="id_type_1">Un professionnel</label>
                </li>
            </ul>
        </div>
        <p id="contact-form-subind" class="left">
            <label for={{ form.subject_ind.id_for_label }}>Sujet :</label>
            {{ form.subject_ind }}
        </p>
        <p id="contact-form-subpro">
            {{ form.subject_pro }}
        </p>
        <p id="contact-form-name">
            {{ form.name }}
        </p>
        <p id="contact-form-email">
            {{ form.email }}
        </p>
        <p id="contact-form-phone">
            {{ form.phone }}
        </p>
        <p id="contact-form-msg">
            {{ form.message }}
        </p>
        <p id="contact-form-copy" class="left">
            <label for={{ form.copy.id_for_label }}>Recevoir une copie</label>
            {{ form.copy }}
        </p>
        <input class="btn btn-lblue" type="submit" value="Envoyer" />
    </form>

pages/templates/pages/form-garden.html
{% load honeypot %}

<div id="garden-form" class="popup">
    <form class="form" action="" method="post">
        <a href="#" class="close close-bk-form" title="Fermer la pop-up">❌</a>
        <h2 class="title h2">Contactez le jardin</h2>
        <hr>
        <p class="info valid center demand-confirmation" hidden="">Votre message a bien était envoyé, nous vous répondrons dans les meilleurs délais</p>
        <p class="info warning center check-something" hidden="">Il y a eu une erreur lors de l'envoi, notre e-mail a@b.c reste disponible</p>
        {% csrf_token %}
        {% render_honeypot_field "firstname" %}
        {{ form_garden.as_p }}
        <input class="btn btn-lblue" type="submit" value="Envoyer" />
    </form>
</div>

pages/templates/pages/garden-project.html
{% extends "core.html" %}

{% block content %}
{% include 'pages/generic.html' %}
{% endblock %}

pages/templates/pages/hello_bot.html
{% extends "core.html" %}

{% block content %}
{% include 'pages/generic.html' %}
{% endblock %}

pages/templates/pages/jobhunt.html
{% extends "core.html" %}

{% block content %}
{% include 'pages/generic.html' %}
{% endblock %}

pages/templates/pages/legal-notice.html
{% extends "core.html" %}

{% block content %}
{% include 'pages/generic.html' %}

<div style="padding: 5vh 15vw;">
    <h2 id="-dition-du-site">Édition du site</h2>
    <p><strong>Abeilles Aide et Entraide</strong><br>
    <strong>E-mail</strong> : contact<i class="fas fa-at"></i>asso-abeilles.fr<br>
    <strong>Téléphone</strong> : 01.69.48.88.43</p>
    <p><strong>Association loi 1901</strong><br>
    <strong>SIRET</strong> n°418 419 438 00050<br>
    <strong>APE</strong> n°8121Z</p>
    <p><strong>Siège social</strong> :<br>
    Abeilles Aide et Entraide<br>
    125 rue Ferdinand Buisson<br>
    91210 Draveil </p>

    <p><strong>Directrice de la publication</strong> :<br>
    Gwenaelle Duchemin</p>


    <h2 id="h-bergement">Hébergement</h2>
    <p>Ce site est hébergé par la société PlanetHoster.<br>
    <strong>Sur ses serveurs francais</strong></p>

    <p><strong>PLANETHOSTER</strong><br>
    <strong>TPS</strong> : 808598932 RT0001<br>
    <strong>TVQ</strong> : 1220427184 TQ0001</p>

    <p>4416 Louis B. Mayer<br>
    Laval (Grand Montréal),<br>
    Québec H7P 0G1
    Canada</p>

    <p><strong>Tél FR</strong> (Nº Vert): 0 805 080 426<br>
    <strong>Tél FR</strong>: +33 1 76 60 41 43<br>
    www.planethoster.com</p>

    <h2 id="propri-t-intellectuelle-et-cr-dits">Propriété intellectuelle et crédits</h2>

    <p>
    Photographies et textes : Abeilles Aide et Entraide<br>
    Code source : Gino Ladowitch & Adrien Kara<br>
    Typographie text &quot;Creato Display&quot; sous licence &quot;SIL OFL 1.1&quot; : Anugrah Pasau<br>
    Typographie icons &quot;Font Awesome 5&quot; sous licence &quot;SIL OFL 1.1 / CC BY 4.0 / MIT&quot;
    </p>

    <p>
    La structure générale du site Internet abeilles-aide-entraide.fr ainsi que l’ensemble des contenus qui y sont diffusés (notamment les images, articles, photographies, illustrations, signes distinctifs, logos, marques, vidéos, interviews, sons et textes, bases de données) sont protégés par la législation en vigueur en France en matière de propriété intellectuelle.
    </p>

    <h2 id="utilisation-des-cookies">Utilisation des Cookies</h2>
    <p>Ce site n&#39;utilise aucun cookie de suivi, d’adaptation du contenue ou de créations de statistiques.
    Seul deux cookies de fonctionnement sont attribue, CSRF (securite), session (pour la connection administrateur)</p>
    <h2 id="-volution-de-la-confidentialit-">Évolution de la confidentialité</h2>
    <p>La présente Politique de confidentialité peut être amenée à évoluer, notamment en raison des évolutions législatives et réglementaires. </p>
    <h2 id="politique-de-confidentialit-">Politique de confidentialité</h2>
    <p>Abeilles Aide et Entraide attache une grande importance à la protection des données à caractère personnel. Dans ce cadre, la présente Politique de confidentialité vous permettra de comprendre quelles données à caractère personnel nous collectons et ce que nous en faisons, ainsi que la façon dont vous pouvez protéger votre vie privée dans le cadre des services que nous fournissons. </p>
    <h3 id="1-quel-sont-les-donn-es-vous-concernant-que-nous-collectons-">1. Quel sont les données vous concernant que nous collectons ?</h3>
    <p>Dans le cadre de la commande d&#39;un service fournis par Abeilles Aide et Entraide, nous collectons les catégories de données suivantes :</p>
    
    <p>- Données <span class="hljs-keyword">d</span>’identification : nom, <span class="hljs-keyword">pr</span>énom, adresse postale et courriel, numéro <span class="hljs-keyword">de</span> té<span class="hljs-keyword">l</span>éphone, numéro client·<span class="hljs-keyword">e</span>·s.<br>
    - Données <span class="hljs-keyword">de</span> paiement : moyen <span class="hljs-keyword">de</span> paiement, factures.<br>
    - Données <span class="hljs-keyword">d</span>’usage : services souscrits, consommations, communications.<br>
    - Données <span class="hljs-keyword">de</span> suivi <span class="hljs-keyword">de</span> <span class="hljs-keyword">la</span> relation Client·<span class="hljs-keyword">e</span> : demandes <span class="hljs-keyword">d</span>’assistance, correspondance avec le·a client·<span class="hljs-keyword">e</span>. 
    </p>
    
    <h3 id="2-de-quelle-fa-on-utilisons-nous-vos-donn-es-">2. De quelle façon utilisons nous vos données ?</h3>
    <p>Abeilles Aide et Entraide utilise vos données pour les besoins de l’exécution et de la gestion du contrat. Ceci comprend la relation contractuelle, l’installation, la maintenance et la gestion du service souscrit ou produit commandé, la délivrance d’une assistance et le traitement de vos demandes, la facturation du service ou produit, la gestion des réclamations, différends et les procédures de recouvrement.</p>
    
    <p>Ces données sont conservées pendant le temps nécessaire à la gestion du contrat et/ou pendant la durée légale. Sans ces données, nous ne pourrions pas honorer les prestations commandées. </p>

    <p>Abeilles Aide et Entraide pourra également utiliser vos données afin de respecter ses obligations légales (incluant les lois anti-fraude, les lois sur le blanchiment d’argent et les dispositions concernant le retard ou l’absence de paiement par le client·e·s) et/ou pour répondre aux demandes des autorités publiques et gouvernementales. </p>

    <h3>3. Comment gérer la collecte et l’utilisation de vos données ?</h3>
    <p>Vous pouvez à tout moment accéder à vos données, les rectifier, demander leur suppression, vous opposer à un traitement pour des motifs légitimes en raison de votre situation particulière ou encore exercer votre droit à la portabilité de vos données, en envoyant un e-mail et un justificatif de votre identité à l’adresse : contact<i class="fas fa-at"></i>asso-abeilles.fr, adresse dédié à la Protection des Données personnelles.
    En cas de réclamation à laquelle Abeilles Aide et Entraide ne vous aurait pas donné de réponse satisfaisante, vous pouvez vous adresser à la Commission Nationale de l’Informatique et des Libertés (CNIL) en charge du respect des obligations en matière de données personnelles. </p>

    <h3>4. De quelle façon la sécurité de vos données est assurée ?</h3>
    <p>Abeilles Aide et Entraide met en œuvre les actions nécessaires afin de protéger les données personnelles qu’elle traite. Vos données sont traitées de façon électronique et/ou manuelle et en tout état de cause, de façon à ce que leur sécurité, protection et confidentialité soient assurées au regard de leur niveau de sensibilité, via des mesures techniques et physiques pour prévenir la perte, le vol, l’utilisation, la divulgation ou encore la modification non-autorisées. </p>

    <h3>5. Qui peut avoir accès à vos données personnelles</h3>
    <p>Vos données personnelles sont traitées par Abeilles Aide et Entraide, ses partenaires, pour les besoins de la gestion du contrat et de l’exécution des prestations que vous avez demandées.
    Sur demande, elles peuvent également être transférées aux personnes et autorités dont le droit d’accès aux données à caractère personnel est reconnu par la loi, les règlements ou les dispositions émanant d’autorités habilitées par la loi. </p>
</div>

{% endblock %}

pages/templates/pages/missions.html
{% extends "core.html" %}

{% block content %}
{% include 'pages/generic.html' %}
{% endblock %}

pages/templates/pages/partners.html
{% extends "core.html" %}

{% block content %}
{% include 'pages/generic.html' %}
{% endblock %}

pages/templates/pages/services-pro.html
{% extends "core.html" %}
{% block content %}
{% include 'pages/generic.html' %}
{% endblock %}

pages/templates/pages/services.html
{% extends "core.html" %}

{% block content %}
{% include 'pages/generic.html' %}
{% endblock %}

pages/templates/pages/values.html
{% extends "core.html" %}

{% block content %}
{% include 'pages/generic.html' %}
{% endblock %}